from __future__ import annotations

import hashlib
import html
import json
import os
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import urlparse


SERVICE_NAME = "CV Generator"
SERVICE_SLUG = "cv-generator"
ALLOWED_FORMATS = {"html", "json", "pdf", "docx"}
DEFAULT_PORT = 8080


def build_cv(payload: dict[str, Any]) -> dict[str, Any]:
    profile = payload.get("profile")
    if not isinstance(profile, dict):
        raise ValueError("profile must be an object")

    export_format = str(payload.get("export_format", "html")).lower()
    if export_format not in ALLOWED_FORMATS:
        raise ValueError("export_format must be one of html, json, pdf, docx")

    name = clean_text(profile.get("name") or "Unnamed Candidate")
    headline = clean_text(profile.get("headline") or profile.get("title") or "Professional Profile")
    summary = clean_text(profile.get("summary") or "")
    experience = normalize_list(profile.get("experience"))
    skills = normalize_list(profile.get("skills"))
    locale = clean_text(payload.get("locale") or "tr-TR")
    template = clean_text(payload.get("template") or "modern")

    html_artifact = render_html(
        name=name,
        headline=headline,
        summary=summary,
        experience=experience,
        skills=skills,
        locale=locale,
        template=template,
    )

    generated_at = datetime.now(timezone.utc).isoformat()
    artifact_hash = hashlib.sha256(html_artifact.encode("utf-8")).hexdigest()[:16]

    return {
        "service": SERVICE_SLUG,
        "status": "generated",
        "id": f"cv_{artifact_hash}",
        "generated_at": generated_at,
        "export_format": export_format,
        "render_mode": "html_artifact",
        "template": template,
        "locale": locale,
        "artifact": {
            "content_type": "text/html; charset=utf-8",
            "filename": f"{slugify(name)}.{extension_for(export_format)}",
            "html": html_artifact,
            "sha256": hashlib.sha256(html_artifact.encode("utf-8")).hexdigest(),
        },
        "profile": {
            "name": name,
            "headline": headline,
            "skills_count": len(skills),
            "experience_count": len(experience),
        },
        "notes": [
            "This runtime returns a portable HTML artifact in v1.",
            "PDF and DOCX binary renderers can be attached later without changing the gateway contract.",
        ],
    }


def clean_text(value: Any) -> str:
    return str(value or "").strip()[:500]


def normalize_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [clean_text(item) for item in value if clean_text(item)][:20]

    if isinstance(value, str) and value.strip():
        return [clean_text(value)]

    return []


def render_html(
    *,
    name: str,
    headline: str,
    summary: str,
    experience: list[str],
    skills: list[str],
    locale: str,
    template: str,
) -> str:
    experience_items = "".join(f"<li>{html.escape(item)}</li>" for item in experience)
    skill_items = "".join(f"<li>{html.escape(item)}</li>" for item in skills)
    summary_block = f"<p>{html.escape(summary)}</p>" if summary else ""

    return f"""<!doctype html>
<html lang="{html.escape(locale[:2] or "en")}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{html.escape(name)} CV</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 0; color: #18212f; background: #f5f7fb; }}
    main {{ max-width: 840px; margin: 0 auto; padding: 40px 28px; background: #ffffff; min-height: 100vh; }}
    header {{ border-bottom: 3px solid #1f7a8c; padding-bottom: 20px; margin-bottom: 28px; }}
    h1 {{ margin: 0 0 8px; font-size: 34px; letter-spacing: 0; }}
    h2 {{ margin-top: 28px; font-size: 18px; color: #1f7a8c; }}
    p, li {{ font-size: 15px; line-height: 1.55; }}
    ul {{ padding-left: 20px; }}
    .meta {{ color: #5b6678; font-size: 13px; }}
  </style>
</head>
<body>
  <main data-template="{html.escape(template)}">
    <header>
      <h1>{html.escape(name)}</h1>
      <p>{html.escape(headline)}</p>
      <div class="meta">Generated by AgentAndBot CV Generator</div>
    </header>
    {summary_block}
    <section>
      <h2>Experience</h2>
      <ul>{experience_items or "<li>Experience details can be added later.</li>"}</ul>
    </section>
    <section>
      <h2>Skills</h2>
      <ul>{skill_items or "<li>Skills can be added later.</li>"}</ul>
    </section>
  </main>
</body>
</html>"""


def extension_for(export_format: str) -> str:
    if export_format in {"pdf", "docx"}:
        return "html"

    return export_format


def slugify(value: str) -> str:
    slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-")
    return "-".join(part for part in slug.split("-") if part) or "cv"


class CvGeneratorHandler(BaseHTTPRequestHandler):
    server_version = "CvGenerator/1.0"

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self.send_common_headers()
        self.end_headers()

    def do_GET(self) -> None:
        path = urlparse(self.path).path

        if path == "/health":
            self.json_response({"status": "ok", "service": SERVICE_SLUG})
        elif path in {"/", "/docs"}:
            self.json_response(
                {
                    "service": SERVICE_SLUG,
                    "name": SERVICE_NAME,
                    "health": "/health",
                    "generate": "/api/generate",
                    "embed": "/embed",
                    "request": {
                        "profile": {"name": "Ada Lovelace", "headline": "AI worker"},
                        "export_format": "html",
                    },
                }
            )
        elif path == "/embed":
            self.html_response(EMBED_HTML)
        else:
            self.json_response({"error": "not_found"}, status=404)

    def do_POST(self) -> None:
        path = urlparse(self.path).path

        if path != "/api/generate":
            self.json_response({"error": "not_found"}, status=404)
            return

        try:
            payload = self.read_json()
            result = build_cv(payload)
        except json.JSONDecodeError:
            self.json_response({"error": "invalid_json"}, status=400)
        except ValueError as exc:
            self.json_response({"error": "invalid_payload", "message": str(exc)}, status=400)
        else:
            self.json_response({"data": result})

    def read_json(self) -> dict[str, Any]:
        length = int(self.headers.get("content-length", "0") or "0")
        if length <= 0:
            return {}

        raw = self.rfile.read(min(length, 1_000_000))
        parsed = json.loads(raw.decode("utf-8"))
        if not isinstance(parsed, dict):
            raise ValueError("JSON body must be an object")

        return parsed

    def json_response(self, payload: dict[str, Any], status: int = 200) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_common_headers()
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def html_response(self, body: str, status: int = 200) -> None:
        raw = body.encode("utf-8")
        self.send_response(status)
        self.send_common_headers()
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def send_common_headers(self) -> None:
        self.send_header("Access-Control-Allow-Origin", os.getenv("CORS_ORIGIN", "*"))
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization, X-API-Key")
        self.send_header("X-Content-Type-Options", "nosniff")

    def log_message(self, format: str, *args: Any) -> None:
        if os.getenv("CV_GENERATOR_ACCESS_LOG", "false").lower() == "true":
            super().log_message(format, *args)


EMBED_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>CV Generator Embed</title>
</head>
<body>
  <form id="cv-form">
    <input name="name" placeholder="Name" />
    <input name="headline" placeholder="Headline" />
    <button type="submit">Generate</button>
  </form>
  <pre id="result"></pre>
  <script>
    document.getElementById("cv-form").addEventListener("submit", async (event) => {
      event.preventDefault();
      const form = new FormData(event.currentTarget);
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify({
          profile: {
            name: form.get("name"),
            headline: form.get("headline")
          },
          export_format: "html"
        })
      });
      document.getElementById("result").textContent = JSON.stringify(await response.json(), null, 2);
    });
  </script>
</body>
</html>"""


def run() -> None:
    port = int(os.getenv("PORT", str(DEFAULT_PORT)))
    server = ThreadingHTTPServer(("0.0.0.0", port), CvGeneratorHandler)
    print(f"{SERVICE_NAME} listening on :{port}", flush=True)
    server.serve_forever()


if __name__ == "__main__":
    run()
